import { useState } from "react";
import {
  AppWindow,
  ChevronDown,
  ChevronUp,
  Clipboard,
  Cpu,
  GitBranch,
  Globe,
  HardDrive,
  ImageIcon,
  Mic,
  Monitor,
  Search,
  Sparkles,
  Terminal,
  Video,
  Wand2,
  Wrench,
} from "lucide-react";

interface Props {
  toolName: string;
  description: string;
  defaultPermission: string;
  override?: { enabled: boolean; require_approval: boolean };
  onOverride: (enabled: boolean, requireApproval: boolean) => void;
}

const toolIcons: Record<string, React.ElementType> = {
  pc: Monitor,
  shell: Terminal,
  wsl: Terminal,
  filesystem: HardDrive,
  browser: Globe,
  process: Cpu,
  system_info: Monitor,
  code_editor: Wand2,
  code_analysis: GitBranch,
  subprocess: Cpu,
  tool_creator: Wrench,
  image_gen: ImageIcon,
  video_gen: Video,
  speak: Mic,
  transcription: Mic,
  web_search: Search,
  openai_computer: Monitor,
  ui_customizer: Sparkles,
  clipboard: Clipboard,
  desktop: Monitor,
  app_manager: AppWindow,
  connector: Globe,
  git: GitBranch,
  worker: Cpu,
  scheduler: Cpu,
  memory: HardDrive,
  workspace_sync: HardDrive,
  web_deploy: Globe,
};

const toolLabels: Record<string, string> = {
  pc: "PC Control",
  wsl: "WSL",
  system_info: "System Info",
  code_editor: "Code Editor",
  code_analysis: "Code Analysis",
  tool_creator: "Tool Creator",
  image_gen: "Image Generation",
  video_gen: "Video Generation",
  web_search: "Web Search",
  openai_computer: "OpenAI Computer Use",
  ui_customizer: "UI Customizer",
  workspace_sync: "Workspace Sync",
  web_deploy: "Web Deploy",
};

const guardrailCopy: Record<string, { summary: string; details?: string }> = {
  pc: {
    summary: "Controls your computer and browser directly.",
    details:
      "Lets the agent open apps, browse websites, click, type, manage files, and carry out step-by-step tasks on your machine.",
  },
  shell: {
    summary: "Runs terminal commands on your computer.",
    details:
      "Useful for installs, scripts, debugging, and automation. This is one of the most powerful permissions because commands can change your system quickly.",
  },
  wsl: {
    summary: "Runs commands inside Windows Subsystem for Linux.",
    details:
      "Best for Linux-based tooling, package managers, and development workflows that should stay inside your WSL environment.",
  },
  filesystem: {
    summary: "Reads, writes, and organizes files and folders.",
    details:
      "Allows the agent to inspect files, create new ones, edit existing content, move data around, and manage directory structure.",
  },
  browser: {
    summary: "Uses the built-in browser automation tools.",
    details:
      "Can open pages, click elements, type into forms, capture screenshots, and navigate the web on your behalf.",
  },
  process: {
    summary: "Views and manages running apps and background tasks.",
    details:
      "Lets the agent inspect active processes and stop stuck or unwanted programs when needed.",
  },
  system_info: {
    summary: "Checks system health and device information.",
    details:
      "Includes things like CPU, memory, disk usage, operating system details, and other environment information.",
  },
  code_editor: {
    summary: "Creates and edits code files safely.",
    details:
      "Built for structured code changes, patching files, and making development edits without relying only on raw shell commands.",
  },
  code_analysis: {
    summary: "Inspects code to understand structure and issues.",
    details:
      "Useful for reviewing functions, classes, dependencies, complexity, and possible bugs before making changes.",
  },
  subprocess: {
    summary: "Runs isolated helper tasks in parallel.",
    details:
      "Lets the agent spin up worker processes for separate jobs without blocking the main task flow.",
  },
  tool_creator: {
    summary: "Creates new custom tools at runtime.",
    details:
      "This allows the agent to write and register brand-new capabilities, so it is a higher-trust permission.",
  },
  image_gen: {
    summary: "Generates or edits images with AI.",
    details:
      "Can create visuals from prompts or modify existing images depending on the workflow.",
  },
  video_gen: {
    summary: "Generates videos with AI.",
    details:
      "Used for video creation workflows, including prompt-based generation and asset assembly.",
  },
  speak: {
    summary: "Turns text into spoken audio.",
    details:
      "Useful for voice output, narration, and audio responses generated by the agent.",
  },
  transcription: {
    summary: "Transcribes speech and audio into text.",
    details:
      "Can convert recordings or voice clips into written text for summarizing, searching, or follow-up actions.",
  },
  web_search: {
    summary: "Searches the web for current information.",
    details:
      "Helpful when the agent needs up-to-date facts, references, or external sources beyond local files.",
  },
  openai_computer: {
    summary: "Uses OpenAI's computer-use workflow for desktop control.",
    details:
      "This is an advanced computer-control path that can observe the screen and act inside desktop apps and websites.",
  },
  ui_customizer: {
    summary: "Edits the Plutus interface itself.",
    details:
      "Lets the agent modify frontend code and restyle or rework parts of the app UI.",
  },
  clipboard: {
    summary: "Reads from and writes to your clipboard.",
    details:
      "Useful for copy-and-paste workflows, but it can also access whatever you copied most recently.",
  },
  desktop: {
    summary: "Interacts with desktop windows and on-screen elements.",
    details:
      "Used for native app control when browser-style automation is not enough.",
  },
  app_manager: {
    summary: "Opens, installs, and manages apps.",
    details:
      "Lets the agent launch applications and, on supported systems, help manage software on the device.",
  },
  connector: {
    summary: "Uses connected external services and integrations.",
    details:
      "This includes sending data to tools like email, chat, APIs, and other linked services configured in Plutus.",
  },
  git: {
    summary: "Works with Git repositories and version control.",
    details:
      "Can inspect repos, make commits, manage branches, and interact with remote Git hosting depending on the task.",
  },
  worker: {
    summary: "Creates and manages background workers.",
    details:
      "Useful for long-running or delegated tasks that should continue outside the main chat flow.",
  },
  scheduler: {
    summary: "Schedules tasks to run later or on a repeat cadence.",
    details:
      "Lets the agent set up one-time or recurring automation, so actions may happen after the current session ends.",
  },
  memory: {
    summary: "Stores and recalls task memory.",
    details:
      "Used to keep track of goals, facts, plans, and conversation context so the agent can stay consistent over time.",
  },
  workspace_sync: {
    summary: "Syncs project files with the connected workspace.",
    details:
      "Allows uploads, downloads, and coordination between the local app and linked cloud workspace.",
  },
  web_deploy: {
    summary: "Publishes web projects to hosting services.",
    details:
      "This can push a built site or app live, so it is best enabled only when you want deployment actions available.",
  },
};

const permissionLabels: Record<string, { label: string; color: string; bg: string }> = {
  allowed: { label: "Allowed", color: "text-emerald-400", bg: "bg-emerald-500/10" },
  requires_approval: { label: "Needs Approval", color: "text-amber-400", bg: "bg-amber-500/10" },
  denied: { label: "Denied", color: "text-red-400", bg: "bg-red-500/10" },
};

function formatToolName(toolName: string) {
  if (toolLabels[toolName]) {
    return toolLabels[toolName];
  }

  return toolName
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function normalizeDescription(description: string) {
  return description.replace(/\s+/g, " ").trim();
}

function shortenDescription(description: string, maxLength = 88) {
  if (description.length <= maxLength) {
    return description;
  }

  return `${description.slice(0, maxLength).trimEnd()}…`;
}

export function PermissionToggle({
  toolName,
  description,
  defaultPermission,
  override,
  onOverride,
}: Props) {
  const [expanded, setExpanded] = useState(false);
  const Icon = toolIcons[toolName] || Terminal;
  const isEnabled = override ? override.enabled : defaultPermission !== "denied";
  const needsApproval = override
    ? override.require_approval
    : defaultPermission === "requires_approval";

  const effectivePermission = !isEnabled
    ? "denied"
    : needsApproval
      ? "requires_approval"
      : "allowed";

  const perm = permissionLabels[effectivePermission] || permissionLabels.denied;
  const curatedCopy = guardrailCopy[toolName];
  const rawDescription = normalizeDescription(description);
  const summary = curatedCopy?.summary || shortenDescription(rawDescription || "No description available.");
  const details = curatedCopy?.details || (rawDescription && rawDescription !== summary ? rawDescription : "");
  const canExpand = Boolean(details);

  return (
    <div
      className={`flex items-start gap-4 p-3.5 rounded-xl border transition-all duration-200 ${
        isEnabled
          ? "bg-gray-800/40 border-gray-700/50 hover:border-gray-600/50"
          : "bg-gray-800/20 border-gray-800/40 opacity-60 hover:opacity-80"
      }`}
    >
      <div
        className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 transition-colors ${
          isEnabled ? "bg-gray-700/60" : "bg-gray-800/60"
        }`}
      >
        <Icon
          className={`w-[18px] h-[18px] transition-colors ${
            isEnabled ? "text-gray-300" : "text-gray-500"
          }`}
        />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span
            className={`text-sm font-medium transition-colors ${
              isEnabled ? "text-gray-200" : "text-gray-400"
            }`}
          >
            {formatToolName(toolName)}
          </span>
          <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${perm.color} ${perm.bg}`}>
            {perm.label}
          </span>
        </div>

        <p className="text-xs text-gray-400 mt-1 leading-relaxed break-words">
          {summary}
        </p>

        {canExpand && expanded && (
          <p className="text-[11px] text-gray-500 mt-2 leading-relaxed break-words animate-fade-in">
            {details}
          </p>
        )}

        {canExpand && (
          <button
            type="button"
            onClick={() => setExpanded((current) => !current)}
            className="inline-flex items-center gap-1.5 mt-2 text-[11px] font-medium text-plutus-300/80 hover:text-plutus-200 transition-colors"
            aria-expanded={expanded}
          >
            {expanded ? (
              <>
                Show less
                <ChevronUp className="w-3.5 h-3.5" />
              </>
            ) : (
              <>
                Show more
                <ChevronDown className="w-3.5 h-3.5" />
              </>
            )}
          </button>
        )}
      </div>

      <div className="flex items-center gap-2.5 flex-shrink-0 pt-0.5">
        {isEnabled && (
          <button
            onClick={() => onOverride(true, !needsApproval)}
            className={`text-xs font-medium px-3 py-1.5 rounded-lg border transition-all duration-200 ${
              needsApproval
                ? "border-amber-500/30 bg-amber-500/10 text-amber-400 hover:bg-amber-500/15 shadow-sm shadow-amber-500/5"
                : "border-gray-700/50 bg-gray-800/50 text-gray-500 hover:text-gray-300 hover:border-gray-600/50"
            }`}
          >
            {needsApproval ? "Approval ON" : "Approval OFF"}
          </button>
        )}

        <button
          onClick={() => onOverride(!isEnabled, needsApproval)}
          className="toggle-switch"
          data-state={isEnabled ? "on" : "off"}
          role="switch"
          aria-checked={isEnabled}
        >
          <span className="toggle-thumb" />
        </button>
      </div>
    </div>
  );
}
